<?php

/**
 * @file
 * Webform Hierarchy module.
 */

/**
 * Implements hook_theme().
 *
 * @inheritdoc
 */
function webform_hierarchy_theme(): array {
  $a = [
    'webform_hierarchy' => [
      'render element' => 'element',
    ],
  ];
  return $a;
}

/**
 * Prepares variables for webform hierarchy template.
 *
 * {@inheritdoc}
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_hierarchy(array &$variables) {
  \Drupal::moduleHandler()->loadInclude('webform', 'inc', 'includes/webform.theme.template');
  _template_preprocess_webform_composite($variables);
}
