theme: current
defaults:
  sender: graphmailer
  formatter: graphmailer
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: graphmailer
      sender: graphmailer
  news_clips: {  }
  system: {  }
